# Generated by Django 3.2.5 on 2021-08-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerOptionId', models.IntegerField(unique=True)),
                ('optionContent', models.CharField(max_length=255)),
                ('completionContent', models.CharField(max_length=255, null=True)),
                ('optionScore', models.CharField(max_length=255, null=True)),
                ('optionScoreText', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaireId', models.IntegerField(unique=True)),
                ('answerId', models.IntegerField(null=True, unique=True)),
                ('commitTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerQuestionId', models.IntegerField(unique=True)),
                ('answerQuestionnaireId', models.IntegerField(unique=True)),
                ('questionTypeId', models.IntegerField(unique=True)),
                ('answerText', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField(unique=True)),
                ('optionOrder', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('optionContent', models.CharField(max_length=255)),
                ('optionScore', models.IntegerField(default=-1)),
                ('optionText', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorId', models.IntegerField(unique=True)),
                ('questionnaireTitle', models.CharField(max_length=32)),
                ('questionnaireInformation', models.CharField(max_length=255)),
                ('setUpTime', models.DateField(auto_now_add=True, null=True)),
                ('latestAlterTime', models.DateField(auto_now=True, null=True)),
                ('maxRecovery', models.IntegerField(default=9999)),
                ('currentState', models.BooleanField(default=True)),
                ('questionAmount', models.IntegerField(default=0)),
                ('recoveryAmount', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaireId', models.IntegerField(unique=True)),
                ('questionTitle', models.CharField(max_length=255)),
                ('questionTypeId', models.IntegerField(unique=True)),
                ('required', models.BooleanField(default=False)),
                ('multipleChoice', models.BooleanField(null=True)),
                ('choiceAmount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('questionTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('questionTypeName', models.CharField(max_length=255)),
            ],
        ),
    ]
