# Generated by Django 3.2.6 on 2021-08-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='authorId',
            field=models.IntegerField(),
        ),
    ]
