# Generated by Django 3.2.5 on 2021-08-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireinformation',
            name='recoveryAmount',
        ),
        migrations.AddField(
            model_name='questionnaireinformation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
