# Generated by Django 3.2.6 on 2021-08-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireinformation',
            name='answerAmount',
            field=models.IntegerField(default=0)
        ),

    ]
