# Generated by Django 3.2.5 on 2021-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0002_auto_20210821_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireinformation',
            name='recoveryAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questionnaireId',
            field=models.IntegerField(),
        ),
    ]
