# Generated by Django 3.2.5 on 2021-08-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0003_auto_20210821_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireinformation',
            name='answerAmount',
        ),
    ]
