# Generated by Django 3.2.5 on 2021-08-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0004_remove_questionnaireinformation_answeramount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questionTypeId',
            field=models.IntegerField(),
        ),
    ]
