# Generated by Django 3.2.5 on 2021-08-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0005_alter_questions_questiontypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='questionId',
            field=models.IntegerField(),
        ),
    ]
