# Generated by Django 3.2.5 on 2021-08-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0006_alter_options_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestionnaire',
            name='questionnaireId',
            field=models.IntegerField(),
        ),
    ]
