# Generated by Django 3.2.5 on 2021-08-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0007_alter_answerquestionnaire_questionnaireid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerquestions',
            name='questionTypeId',
        ),
    ]
