# Generated by Django 3.2.5 on 2021-08-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0008_remove_answerquestions_questiontypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestions',
            name='questionTypeId',
            field=models.IntegerField(default=1),
        ),
    ]
