# Generated by Django 3.2.5 on 2021-08-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0009_answerquestions_questiontypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestions',
            name='answerQuestionnaireId',
            field=models.IntegerField(),
        ),
    ]
