# Generated by Django 3.2.5 on 2021-08-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0010_alter_answerquestions_answerquestionnaireid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestions',
            name='answerQuestionId',
            field=models.IntegerField(),
        ),
    ]
