# Generated by Django 3.2.5 on 2021-08-21 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0012_auto_20210821_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroptions',
            name='answerOptionOrder',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='answerQuestionId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='optionType',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='endTime',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 16, 56, 55, 282812)),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='lastEndTime',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 16, 56, 55, 282812)),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 16, 56, 55, 282812)),
        ),
    ]
