# Generated by Django 3.2.5 on 2021-08-21 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0013_auto_20210821_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroptions',
            name='answerOptionOrder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answeroptions',
            name='answerQuestionId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answeroptions',
            name='optionType',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='endTime',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 16, 57, 32, 917675)),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='lastEndTime',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 16, 57, 32, 917675)),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 16, 57, 32, 917675)),
        ),
    ]
