# Generated by Django 3.2.5 on 2021-08-21 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0014_auto_20210821_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroptions',
            name='answerOptionId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='endTime',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 16, 58, 22, 66646)),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='lastEndTime',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 16, 58, 22, 66646)),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 16, 58, 22, 66646)),
        ),
    ]
