# Generated by Django 3.2.5 on 2021-08-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0016_auto_20210821_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='lastEndTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
    ]
