# Generated by Django 3.2.5 on 2021-08-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0018_alter_questionnaireinformation_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
    ]
