# Generated by Django 3.2.5 on 2021-08-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0019_alter_questionnaireinformation_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='endTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='lastEndTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='latestAlterTime',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='setUpTime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireinformation',
            name='startTime',
            field=models.DateField(null=True),
        ),
    ]
