# Generated by Django 3.2.5 on 2021-08-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='abc', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='abc', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='sfID',
            field=models.CharField(default='abc', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='abc', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='abc', max_length=64),
        ),
    ]
