# Generated by Django 3.2.5 on 2021-08-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210817_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sfID',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
